app:
  jwt:
    key: 12e90b8e74f20fc0a7274cff9fcbae14592db12292757f1ea0d7503d30799fd2
  version: v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactions
    username: admin
    password: admin

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.connection.CharSet: UTF-8
  flyway:
    enabled: true
  threads:
    virtual:
      enabled: true